export default function CateMate() {
  return <main className="project-case cate-case">
    <nav className="case-nav"><a href="/#work">← Back to portfolio</a><span>CateMate / Case study</span><a href="https://github.com/coco20020806/CateMate" target="_blank" rel="noreferrer">GitHub ↗</a></nav>
    <section className="project-hero cate-hero"><div><p className="case-kicker">AI CATEGORY ANALYSIS · 0 → 1 PROTOTYPE</p><p className="case-wordmark">Cate<span>Mate</span></p><h1>让分析需求<br/><em>有迹可循。</em></h1><p className="case-lead">面向品类策略分析的 AI 原型：将模糊的自然语言提需，转化为可确认、可执行、可回溯的分析工作流。</p><div className="case-actions"><a href="https://github.com/coco20020806/CateMate" target="_blank" rel="noreferrer">Explore on GitHub ↗</a><a href="#tech">See the system ↓</a></div></div><div className="cate-terminal"><small>analysis-request / draft</small><p>“帮我分析新加坡市场<br/>文具类目的近期趋势”</p><hr/><small>STRUCTURED TASK</small><div><b>SG</b><b>Stationery</b><b>Trend</b><b>Top SKU</b></div><em>● Ready for confirmation</em></div></section>
    <section className="case-section"><p className="case-kicker">THE PROBLEM</p><div className="case-inner case-split"><h2>分析不该是<br/>一次性的<strong>回答。</strong></h2><div><p>业务中的“帮我看看这个类目”常常包含尚未说清楚的范围、指标与判断口径。直接生成答案很快，却难以复用、审计或纠错。</p><p>CateMate 让 AI 负责理解与编排；把确定性的计算、口径与留痕留给可验证的系统。</p></div></div></section>
    <section className="case-section dark cate-tech" id="tech"><p className="case-kicker">ONE TECHNICAL FLOW</p><div className="case-inner"><h2>From a question<br/>to a <em>traceable answer.</em></h2><div className="tech-flow"><article><span>INPUT</span><b>自然语言提需</b><small>market · category · intent</small></article><i>→</i><article><span>UNDERSTAND</span><b>LLM 需求解析</b><small>scope · metrics · plan</small></article><i>→</i><article><span>CONFIRM</span><b>人工确认节点</b><small>business boundary</small></article><i>→</i><article><span>COMPUTE</span><b>Python / SQL</b><small>deterministic modules</small></article><i>→</i><article><span>TRACE</span><b>分析结果与留痕</b><small>sources · artifacts · audit</small></article></div><div className="tech-guard"><b>DESIGN PRINCIPLE</b><span>LLM for understanding & orchestration · code for computation · human for judgment</span></div></div></section>
    <section className="case-section"><p className="case-kicker">CURRENT STATE</p><div className="case-inner results-head"><h2>先让可靠性<br/><em>走在前面。</em></h2><p>已完成趋势分析与 Top SKU 洞察模块的本地数据原型与审计，并将部分高不确定场景收敛为固定工作流。</p></div><div className="case-inner case-stats"><div><strong>02</strong><span>core modules prototyped</span></div><div><strong>0 → 1</strong><span>product & engineering</span></div><div><strong>LOCAL</strong><span>prototype data environment</span></div></div></section>
    <section className="case-section mint"><p className="case-kicker">MY ROLE</p><div className="case-inner case-split"><h2>Designing AI<br/>with <em>boundaries.</em></h2><div><p>独立完成需求抽象、工作流与数据模块设计、原型开发、测试与审计思路梳理。核心关注点不是“能不能生成”，而是结果能否被确认、复用与追溯。</p><a className="case-link" href="https://github.com/coco20020806/CateMate" target="_blank" rel="noreferrer">Explore GitHub ↗</a></div></div></section>
    <footer className="case-footer"><a href="/#work">← Return to KFC&apos;s portfolio</a><span>CateMate · AI, with a paper trail.</span></footer>
  </main>;
}
