export default function BeautyDecode() {
  return <main className="project-case beauty-case">
    <nav className="case-nav"><a className="beauty-action beauty-back" href="/#work">← Back to portfolio</a><span>Beauty Decode / Case study</span><a className="beauty-action" href="http://beautyforhackthon.xyz/" target="_blank" rel="noreferrer">Visit product ↗</a></nav>
    <section className="project-hero beauty-hero"><div><p className="case-kicker">MULTIMODAL BEAUTY AGENT · FULL-STACK BUILD</p><p className="beauty-wordmark">每妆<em>小解</em></p><h1>把看过的<br/><em>美妆教程用起来。</em></h1><p className="case-lead">把一次性美妆视频消费，转化为能够理解、复用、微调与练习的个人美妆学习体验。</p><div className="case-actions"><a className="beauty-action" href="http://beautyforhackthon.xyz/demo/index.html#upload" target="_blank" rel="noreferrer">Open demo ↗</a><a className="beauty-action" href="https://my.feishu.cn/wiki/IkG4wCNV7ilb2gkE0fFcD6Xonud" target="_blank" rel="noreferrer">Demo video ↗</a><a className="beauty-action" href="#tech">See the system ↓</a></div></div><figure className="beauty-board"><img src="/beautydecode-hero-product.png" alt="每妆小解产品主视觉与功能概览"/></figure></section>
    <section className="case-section"><p className="case-kicker">THE INSIGHT</p><div className="case-inner case-split"><h2 className="beauty-insight-title">看懂 <strong>≠</strong> 复用。</h2><div><p>我们日常刷到许多美妆视频，却往往刷后就忘，收藏越多，反而越难再次使用。</p><p>每妆小解将每个美妆视频里的“灵感”和步骤，转化成可以跟随、调整、积累的个人学习资产，为你保存为图例和视频切片，在你需要时随时学习、自由组合，跟随自定义妆容美美完妆。</p></div></div></section>
    <section className="case-section dark beauty-tech" id="tech"><p className="case-kicker">ONE TECHNICAL FLOW</p><div className="case-inner"><h2>From a video<br/>to a <em>personal guide.</em></h2><div className="tech-flow beauty-tech-flow"><article><span>INPUT</span><b>教程视频 / 自拍</b><small>video · user photo</small></article><i>→</i><article><span>PARSE</span><b>抽帧 + ASR</b><small>keyframes · transcript</small></article><i>→</i><article><span>MAP</span><b>Tutorial 映射</b><small>structured tutorial.json</small></article><i>→</i><article><span>UNDERSTAND</span><b>多模态理解</b><small>product · technique · range</small></article><i>→</i><article><span>PREVIEW</span><b>预览 / 跟练</b><small>preview · step diagrams</small></article></div><div className="tech-guard"><b>VERSIONED ARTIFACTS</b><span>schema · semantic validation · selfie QA · fallback · progress / ETA · manifest</span></div></div></section>
    <section className="case-section beauty-live"><p className="case-kicker">IN THE PRODUCT</p><div className="case-inner"><div className="beauty-live-head"><h2>From upload<br/>to a <em>guided routine.</em></h2><p>真实界面覆盖上传、个人美妆档案、图示化教程、解析完成与妆容预览，让每一步都看得见。</p></div><figure><img src="/beautydecode-live-pages.png" alt="每妆小解真实移动端界面：上传教程、妆容档案、图示教程、解析完成和妆容预览" /><figcaption>Live product screens · mobile web</figcaption></figure></div></section>
    <section className="case-section blush"><p className="case-kicker">MY ROLE</p><div className="case-inner case-split"><h2>Build the idea,<br/>then make it <em>usable.</em></h2><div><p>负责全部开发工作，并参与产品定义。完成视频抽帧、ASR、多模态理解、教程映射、妆容预览、图示生成、FastAPI 服务与 React 前端的全链路开发和联调。</p><div className="beauty-skills"><p className="case-kicker">CORE SKILLS / IN SEQUENCE</p><ol><li><b>beauty-video-parse</b><span>解析上传教程视频，抽取关键帧、字幕 / 口播与时间轴。</span></li><li><b>makeup-understanding</b><span>理解妆容结构、部位、技法、风格与产品线索。</span></li><li><b>tutorial-mapper</b><span>映射为结构化 <em>tutorial.json</em>。</span></li><li><b>picture_makeup</b><span>根据教程步骤生成原始图示教程。</span></li><li><b>makeup-visual-optimization</b><span>基于偏好、场景、保留部位与脸部目标生成优化图示 patch。</span></li><li><b>kol-makeup-preview</b><span>生成妆后预览或 KOL 妆容迁移效果。</span></li></ol></div></div></div></section>
    <section className="beauty-link-hub" aria-label="Beauty Decode project links"><p>EXPLORE THE PROJECT</p><div><a className="beauty-action" href="http://beautyforhackthon.xyz/demo/index.html#upload" target="_blank" rel="noreferrer">Visit demo ↗</a><a className="beauty-action" href="https://my.feishu.cn/wiki/IkG4wCNV7ilb2gkE0fFcD6Xonud" target="_blank" rel="noreferrer">Demo video ↗</a><a className="beauty-action" href="http://beautyforhackthon.xyz/" target="_blank" rel="noreferrer">View product ↗</a><a className="beauty-action" href="https://my.feishu.cn/wiki/IkG4wCNV7ilb2gkE0fFcD6Xonud" target="_blank" rel="noreferrer">View product documentation ↗</a><a className="beauty-action" href="https://github.com/coco20020806/BeautyGenius" target="_blank" rel="noreferrer">View GitHub ↗</a></div></section>
    <footer className="case-footer"><a href="/#work">← Return to KFC&apos;s portfolio</a><span>Beauty Decode · make inspiration actionable.</span></footer>
  </main>;
}
