export default function BeautyDecode() {
  return <main className="project-case beauty-case">
    <nav className="case-nav"><a className="beauty-action beauty-back" href="/">← Back to portfolio</a><span>Beauty Decode / Case study</span><a className="beauty-action" href="http://beautyforhackthon.xyz/" target="_blank" rel="noreferrer">Visit demo ↗</a></nav>
    <section className="project-hero beauty-hero"><div><p className="case-kicker">MULTIMODAL BEAUTY AGENT · FULL-STACK BUILD</p><p className="beauty-wordmark">每妆<em>小解</em></p><h1>把看过的<br/><em>美妆教程用起来。</em></h1><p className="case-lead">把一次性美妆视频消费，转化为能够理解、复用、微调与练习的个人美妆学习体验。</p><div className="case-actions"><a className="beauty-action" href="http://beautyforhackthon.xyz/" target="_blank" rel="noreferrer">Open demo ↗</a><a className="beauty-action" href="#tech">See the system ↓</a></div></div><figure className="beauty-board"><img src="/beautydecode-board.png" alt="每妆小解的美妆教程与技法库设计画面"/></figure></section>
    <section className="case-section"><p className="case-kicker">THE INSIGHT</p><div className="case-inner case-split"><h2>看懂，并不等于<br/>能够<strong>复用。</strong></h2><div><p>用户可以看懂一支美妆视频，却难以判断步骤、产品与妆容是否适合自己；收藏越多，反而越难再次使用。</p><p>每妆小解将视频里的“灵感”，转化成可以跟随、调整、积累的个人学习资产。</p></div></div></section>
    <section className="case-section dark beauty-tech" id="tech"><p className="case-kicker">ONE TECHNICAL FLOW</p><div className="case-inner"><h2>From a video<br/>to a <em>personal guide.</em></h2><div className="tech-flow beauty-tech-flow"><article><span>INPUT</span><b>教程视频 / 自拍</b><small>video · user photo</small></article><i>→</i><article><span>PARSE</span><b>抽帧 + ASR</b><small>keyframes · transcript</small></article><i>→</i><article><span>MAP</span><b>Tutorial 映射</b><small>structured tutorial.json</small></article><i>→</i><article><span>UNDERSTAND</span><b>多模态理解</b><small>product · technique · range</small></article><i>→</i><article><span>PREVIEW</span><b>预览 / 跟练</b><small>preview · step diagrams</small></article></div><div className="tech-guard"><b>VERSIONED ARTIFACTS</b><span>schema · semantic validation · selfie QA · fallback · progress / ETA · manifest</span></div></div></section>
    <section className="case-section blush"><p className="case-kicker">MY ROLE</p><div className="case-inner case-split"><h2>Build the idea,<br/>then make it <em>usable.</em></h2><div><p>负责全部开发工作，并参与产品定义。完成视频抽帧、ASR、多模态理解、教程映射、妆容预览、图示生成、FastAPI 服务与 React 前端的全链路开发和联调。</p><a className="beauty-action" href="http://beautyforhackthon.xyz/" target="_blank" rel="noreferrer">Visit demo ↗</a></div></div></section>
    <footer className="case-footer"><a href="/">← Return to KFC&apos;s portfolio</a><span>Beauty Decode · make inspiration actionable.</span></footer>
  </main>;
}
